spring.application.name=emp-management
server.port=8080

# =========================
# Employee DB
# =========================
employee.datasource.jdbc-url=jdbc:mysql://localhost:3306/employee_db
employee.datasource.username=root
employee.datasource.password=123456

# =========================
# Audit DB
# =========================
#audit.datasource.url=jdbc:mysql://localhost:3306/audit_db
#audit.datasource.username=root
#audit.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true